version: "3.1"
services:
  ath_feeder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ath_feeder
    volumes:
      - /path/to/db:/app/db
    env_file:
      - .env
    restart: always
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: 100m
